# default params in the original sc_lio_sam, which is suitable for the dataset: walking, park, garden
# this param set is mainly used for testing. One can use garden dataset for testing, since it's the shortest one among the threes.

sc_lio_sam:

  # Topics
  pointCloudTopic: "/points_raw"               # Point cloud data
  imuTopic: "/imu_raw"                         # IMU data
  odomTopic: "odometry/imu"                   # IMU pre-preintegration odometry, same frequency as IMU

  # Frames
  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"
  
  # Export settings
  saveMap: true                              # https://github.com/TixiaoShan/LIO-SAM/issues/3
  mapDirectory: "/home/yan/lidar_slam/SC-LIO-SAM_test/"  # use global path, and end with "/" 
    # warning: if you have already data in the above savePCDDirectory, it will all remove and remake them. Thus, backup is recommended if pre-made data exist. 

  # Sensor Settings
  sensor: velodyne                            # lidar sensor type, either 'velodyne' or 'ouster'
  N_SCAN: 16                               # number of lidar channel (i.e., 16, 32, 64, 128)
  Horizon_SCAN: 1800                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048)
  downsampleRate: 1                           # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1
  lidarMinRange: 1.0                          # default: 1.0, minimum lidar range to be used
  lidarMaxRange: 1000.0                       # default: 1000.0, maximum lidar range to be used

  # IMU Settings
  imuHz: 500                                  # IMU frequency
  imuAccNoise: 3.9939570888238808e-03
  imuGyrNoise: 1.5636343949698187e-03
  imuAccBiasN: 6.4356659353532566e-05
  imuGyrBiasN: 3.5640318696367613e-05
  imuGravity: 9.80511
  imuRPYWeight: 0.01

  # Extrinsics (lidar -> IMU)
  extrinsicTrans: [0.0, 0.0, 0.0]
  extrinsicRot: [-1, 0, 0,
                  0, 1, 0,
                  0, 0, -1]
  extrinsicRPY: [0, -1, 0,
                 1, 0, 0,
                 0, 0, 1]

  # LOAM feature threshold
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter paprams
  odometrySurfLeafSize: 0.4                     # default: 0.4 - outdoor, 0.2 - indoor
  mappingCornerLeafSize: 0.2                    # default: 0.2 - outdoor, 0.1 - indoor
  mappingSurfLeafSize: 0.4                      # default: 0.4 - outdoor, 0.2 - indoor
  mappingSCLeafSize: 0.5                        # scan context leaf size
  mappingICPLeafSize: 0.4                       # ICP leaf size

  # robot motion constraint (in case you are using a 2D robot)
  z_tollerance: 1000                            # meters
  rotation_tollerance: 1000                     # radians

  # CPU Params
  numberOfCores: 16                              # number of cores for mapping optimization
  mappingProcessInterval: 0.15                  # seconds, regulate mapping frequency

  # Surrounding map
  surroundingkeyframeAddingDistThreshold: 1.0   # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 0.2  # radians, regulate keyframe adding threshold
  surroundingKeyframeDensity: 2.0               # meters, downsample surrounding keyframe poses   
  surroundingKeyframeSearchRadius: 50.0         # meters, within n meters scan-to-map optimization

  # Loop closure
  loopClosureEnableFlag: true
  loopClosureFrequency: 1.0                     # Hz, regulate loop closure constraint add frequency
  historyKeyframeSearchRadius: 15.0             # meters, key frame that is within n meters from current pose will be considerd for loop closure
  historyKeyframeSearchTimeDiff: 30.0           # seconds, key frame that is n seconds older will be considered for loop closure
  historyKeyframeSearchNum: 25                  # number of history key frames will be fused into a submap for loop closure
  historyKeyframeFitnessScore: 0.3              # icp threshold, the smaller the better alignment

  # Visualization
  globalMapVisualizationSearchRadius: 1000.0    # meters, global map visualization radius
  globalMapVisualizationPoseDensity: 10.0       # meters, global map visualization keyframe density
  globalMapVisualizationLeafSize: 0.2           # meters, global map visualization cloud density

  # Threshold for skipping current lidar frame（这些阈值需要根据实际情况测试）
  imuVelThre: 30.0                              # velocity of current lidar frame (opt 预积分器优化后的速度)
  imuAccBiasThre: 1.0                           # opt 预积分器优化后的加速度 bias
  imuGyroBiasThre: 1.0                          # opt 预积分器优化后的陀螺仪 bias
  imuRotVelXThre: 0.52                          # 假设 imu 的安装方式是绕 X 轴旋转是 roll 角，这里就是当前帧 roll 平均角速度上限，设置为 30°/s (i.e. 0.52 rad/s)
  imuRotVelYThre: 1.04                          # 绕 Y 轴转，pitch 角，设置为 60°/s (i.e. 1.04 rad/s) ************重点关注************
  imuRotVelZThre: 3.14                          # 绕 Z 轴转，yaw 角，设置为 180°/s (i.e. 3.14 rad/s)

  # denseMap params
  saveDenseMap: true
  mappingDenseLeafSize: 0.001                    # dense map leaf size
  floorZ: -0.6                                  # meters, floor height (relative to the cooridnate origin of lidar)
  ceilingZ: 1.0                                 # meters, ceiling height (relative to the cooridnate origin of lidar)
  denseMapRange: 5.0                          # meters, only use points within this range for dense map