# params used for dashgo d1

sc_lio_sam:
  # Topics
  pointCloudTopic: "/velodyne_points" # Point cloud data
  imuTopic: "/handsfree/imu" # IMU data
  odomTopic: "odom" # IMU pre-preintegration odometry, same frequency as IMU

  # Frames
  lidarFrame: "base_footprint"
  baselinkFrame: "base_footprint"
  odometryFrame: "odom"
  mapFrame: "map3D"

  # Export settings
  saveMap: true
  mapDirectory: "/home/yan/data/pavilion/map_2023-6-10-16-00_sc0.1_searchRadius5_SC+RSLoop/" # use global path, and end with "/"

  # Sensor Settings
  sensor: velodyne # lidar sensor type, either 'velodyne' or 'ouster'
  N_SCAN: 16 # number of lidar channel (i.e., 16, 32, 64, 128)
  Horizon_SCAN: 1800 # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048)
  downsampleRate: 1 # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1
  lidarMinRange: 0.4 # default: 1.0, minimum lidar range to be used
  lidarMaxRange: 1000.0 # default: 1000.0, maximum lidar range to be used

  # IMU Settings
  imuHz: 300                                  # IMU frequency
  imuAccNoise: 3.6225352484975402e-02
  imuGyrNoise: 2.1908348958778684e-03
  imuAccBiasN: 4.2833363074887498e-04
  imuGyrBiasN: 2.3231160338278684e-05
  imuGravity: -9.8
  imuRPYWeight: 0.01

  # Extrinsics (lidar -> IMU)
  # extrinsicTrans: [-0.15694938, 0.01003531, -0.12693807]
  # extrinsicRot: [0.99733285, -0.07067747, -0.01821735,
  #                 -0.0708193, -0.99746274, -0.00726044,
  #                 -0.01765798, 0.00853122, -0.99980769]
  # extrinsicRPY: [0.99733285, -0.07067747, -0.01821735,
  #                 -0.0708193, -0.99746274, -0.00726044,
  #                 -0.01765798, 0.00853122, -0.99980769]

  # extrinsicTrans: [-0.15328172, -0.02238192, -0.12981084]
  # extrinsicRot: [0.98817724, 0.15331327, -0.00088088,
  #                 0.1533139, -0.98812011, 0.01065335,
  #                 0.00076289, -0.01066245, -0.99994286]
  # extrinsicRPY: [0.98817724, 0.15331327, -0.00088088,
  #                 0.1533139, -0.98812011, 0.01065335,
  #                 0.00076289, -0.01066245, -0.99994286]

  extrinsicTrans: [0.0, 0.0, 0.0]
  # extrinsicTrans: [-0.155, 0.0, -0.1297]
  extrinsicRot: [1, 0, 0,
                  0, -1, 0,
                  0, 0, -1]
  extrinsicRPY: [1, 0, 0,
                  0, -1, 0,
                  0, 0, -1]

  # LOAM feature threshold
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter params
  # odometrySurfLeafSize: 0.05 # default: 0.4 - outdoor, 0.2 - indoor
  # mappingCornerLeafSize: 0.025 # default: 0.2 - outdoor, 0.1 - indoor
  # mappingSurfLeafSize: 0.05 # default: 0.4 - outdoor, 0.2 - indoor
  # mappingSCLeafSize: 0.5 # scan context leaf size
  # mappingICPLeafSize: 0.05 # ICP leaf size

  odometrySurfLeafSize: 0.1 # default: 0.4 - outdoor, 0.2 - indoor
  mappingCornerLeafSize: 0.05 # default: 0.2 - outdoor, 0.1 - indoor
  mappingSurfLeafSize: 0.1 # default: 0.4 - outdoor, 0.2 - indoor
  mappingSCLeafSize: 0.1 # scan context leaf size
  mappingICPLeafSize: 0.1 # ICP leaf size

  # odometrySurfLeafSize: 0.2 # default: 0.4 - outdoor, 0.2 - indoor
  # mappingCornerLeafSize: 0.1 # default: 0.2 - outdoor, 0.1 - indoor
  # mappingSurfLeafSize: 0.2 # default: 0.4 - outdoor, 0.2 - indoor
  # mappingSCLeafSize: 0.5 # scan context leaf size
  # mappingICPLeafSize: 0.2 # ICP leaf size

  # odometrySurfLeafSize: 0.4 # default: 0.4 - outdoor, 0.2 - indoor
  # mappingCornerLeafSize: 0.2 # default: 0.2 - outdoor, 0.1 - indoor
  # mappingSurfLeafSize: 0.4 # default: 0.4 - outdoor, 0.2 - indoor
  # mappingSCLeafSize: 0.5 # scan context leaf size
  # mappingICPLeafSize: 0.4 # ICP leaf size

  # robot motion constraint (in case you are using a 2D robot)
  z_tollerance: 1000 # meters
  rotation_tollerance: 1000 # radians

  # CPU Params
  numberOfCores: 8 # number of cores for mapping optimization
  mappingProcessInterval: 0.05 # seconds, regulate mapping frequency

  # Surrounding map
  surroundingkeyframeAddingDistThreshold: 1.0 # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 0.2 # radians, regulate keyframe adding threshold
  surroundingKeyframeDensity: 2.0 # meters, downsample surrounding keyframe poses
  surroundingKeyframeSearchRadius: 50.0 # meters, within n meters scan-to-map optimization (when loop closure disabled)

  # Loop closure
  loopClosureEnableFlag: true
  loopClosureFrequency: 1.0 # Hz, regulate loop closure constraint add frequency
  historyKeyframeSearchRadius: 5.0 # meters, key frame that is within n meters from current pose will be considerd for loop closure
  historyKeyframeSearchTimeDiff: 30.0 # seconds, key frame that is n seconds older will be considered for loop closure
  historyKeyframeSearchNum: 25 # number of history key frames will be fused into a submap for loop closure
  historyKeyframeFitnessScore: 0.3 # icp threshold, the smaller the better alignment

  # Visualization
  globalMapVisualizationSearchRadius: 1000.0 # meters, global map visualization radius
  globalMapVisualizationPoseDensity: 10.0 # meters, global map visualization keyframe density
  globalMapVisualizationLeafSize: 0.2 # meters, global map visualization cloud density

  # Threshold for skipping current lidar frame（这些阈值需要根据实际情况测试）
  imuVelThre: 3.0 # velocity of current lidar frame (opt 预积分器优化后的速度)
  imuAccBiasThre: 1.0 # opt 预积分器优化后的加速度 bias
  imuGyroBiasThre: 1.0 # opt 预积分器优化后的陀螺仪 bias

  # denseMap params
  saveDenseMap: true
  mappingDenseLeafSize: 0.05 # dense map leaf size
  localDenseMapRange: 5.0 # meters, within this range, wider Z range will be used for dense map, supposing the ground is almost flat
  localMinZ: -0.5 # meters, minimum Z in the local aera (relative to the cooridnate origin of lidar)
  localMaxZ: 0.5 # meters, floor height (relative to the cooridnate origin of lidar)
  globalDenseMapRange: 100.0 # meters, within this range, less wider Z range will be used for dense map, since the ground is not strictly flat
  globalMinZ: -0.3 # meters, ceiling height (relative to the cooridnate origin of lidar)
  globalMaxZ: 1.0
  
